
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class busInformation extends javax.swing.JInternalFrame {
    private DefaultTableModel originalModel;
    /**
     * Creates new form busInformation
     */
    public busInformation() {
        initComponents();
        displayBusInformation();
    }
    private void displayBusInformation() {
        originalModel = (DefaultTableModel) jTable1.getModel(); // Store the original model
        originalModel.setRowCount(0); // Clear existing rows

        try (BufferedReader br = new BufferedReader(new FileReader("busInformation.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split("\\*"); // Assuming data is separated by '*'
                originalModel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void resetTable() {
        jTable1.setModel(originalModel); // Reset the table to its original model
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bus Information Management");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unit", "Serial Number", "Driver", "Passenger Assistant", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String searchText = searchTF.getText().trim();

        // If the search text is empty, display all rows
        if (searchText.isEmpty()) {
            resetTable();
            return;
        }

        DefaultTableModel originalModel = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel filteredModel = new DefaultTableModel();

        // Copy the column names to the filtered model
        for (int col = 0; col < originalModel.getColumnCount(); col++) {
            filteredModel.addColumn(originalModel.getColumnName(col));
        }

        // Iterate through the rows of the original model to find matches
        for (int row = 0; row < originalModel.getRowCount(); row++) {
            boolean rowFound = false;
            for (int col = 0; col < originalModel.getColumnCount(); col++) {
                Object cellValue = originalModel.getValueAt(row, col);
                if (cellValue != null && cellValue.toString().toLowerCase().contains(searchText.toLowerCase())) {
                    rowFound = true;
                    break;
                }
            }
            // If the row matches the search criteria, add it to the filtered model
            if (rowFound) {
                Object[] rowData = new Object[originalModel.getColumnCount()];
                for (int col = 0; col < originalModel.getColumnCount(); col++) {
                    rowData[col] = originalModel.getValueAt(row, col);
                }
                filteredModel.addRow(rowData);
            }
        }

        // Set the filtered model to the table
        jTable1.setModel(filteredModel);

        // If no match is found, display a message
        if (filteredModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No matching record found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchTF;
    // End of variables declaration//GEN-END:variables
}
